web: cd narinocultura_backend && python manage.py migrate && python manage.py create_admin && daphne -b 0.0.0.0 -p $PORT config.asgi:application
worker: cd narinocultura_backend && celery -A config.celery worker --beat --loglevel=warning
