# Generated by Django 5.2.13 on 2026-04-21 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='artists.artistprofile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artistprofile',
            index=models.Index(fields=['slug'], name='artists_art_slug_0ebf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='artistprofile',
            index=models.Index(fields=['is_public'], name='artists_art_is_publ_014145_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['artist', '-created_at'], name='artists_fol_artist__8adf4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'artist'), name='uniq_follow_follower_artist'),
        ),
    ]
