# Generated by Django 5.1.7 on 2026-05-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='artworks/covers/'),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='artworks/gallery/'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
