# Generated by Django 5.2.13 on 2026-04-21 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_highest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'ends_at'], name='auctions_au_status_bfe174_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['seller', '-created_at'], name='auctions_au_seller__f01ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='auctions_bi_auction_5888cb_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-created_at'], name='auctions_bi_auction_c0bb90_idx'),
        ),
    ]
