# Generated by Django 5.1.7 on 2026-05-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20),
        ),
    ]
