# Generated by Django 5.1.7 on 2026-05-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_musicians',
            field=models.ManyToManyField(blank=True, related_name='events', to='musicians.musicianprofile'),
        ),
    ]
