# Generated by Django 5.1.7 on 2026-05-23 23:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Género Musical',
                'verbose_name_plural': 'Géneros Musicales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artistic_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('aggregation_type', models.CharField(choices=[('SOLISTA', 'Solista'), ('BANDA', 'Banda'), ('DJ', 'DJ'), ('COLECTIVO', 'Colectivo'), ('DUO', 'Dúo'), ('TRIO', 'Trío')], default='SOLISTA', max_length=20)),
                ('city', models.CharField(default='Pasto', max_length=100)),
                ('region', models.CharField(default='Nariño', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('founding_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('soundcloud_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('tiktok_handle', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('booking_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('profile_image', models.FileField(blank=True, upload_to='musicians/profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('genres', models.ManyToManyField(blank=True, related_name='musicians', to='musicians.musicgenre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicianFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician_follows', to=settings.AUTH_USER_MODEL)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='musicians.musicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('VIDEO', 'Video Musical'), ('LIVE', 'Presentación En Vivo'), ('STUDIO', 'Grabación de Estudio'), ('COVER', 'Cover / Versión'), ('PODCAST', 'Podcast / Entrevista')], max_length=20)),
                ('youtube_url', models.URLField(blank=True)),
                ('soundcloud_embed', models.URLField(blank=True)),
                ('spotify_track_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='musicians/audio/')),
                ('thumbnail', models.FileField(blank=True, upload_to='musicians/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='musicians.musicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicianReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='musicians.musicianprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='musicianprofile',
            index=models.Index(fields=['slug'], name='musicians_m_slug_328fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='musicianprofile',
            index=models.Index(fields=['city', 'is_active'], name='musicians_m_city_5f6084_idx'),
        ),
        migrations.AddIndex(
            model_name='musicianprofile',
            index=models.Index(fields=['aggregation_type', 'is_active'], name='musicians_m_aggrega_a53ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='musicianprofile',
            index=models.Index(fields=['-popularity_score'], name='musicians_m_popular_f3e04a_idx'),
        ),
        migrations.AddIndex(
            model_name='musicianfollower',
            index=models.Index(fields=['musician', '-followed_at'], name='musicians_m_musicia_f83f59_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicianfollower',
            constraint=models.UniqueConstraint(fields=('user', 'musician'), name='uniq_musician_follower'),
        ),
        migrations.AddIndex(
            model_name='musicalwork',
            index=models.Index(fields=['musician', '-created_at'], name='musicians_m_musicia_808925_idx'),
        ),
        migrations.AddIndex(
            model_name='musicalwork',
            index=models.Index(fields=['work_type'], name='musicians_m_work_ty_2c0ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='musicianreview',
            index=models.Index(fields=['musician', '-created_at'], name='musicians_m_musicia_1ad7fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicianreview',
            constraint=models.UniqueConstraint(fields=('musician', 'reviewer'), name='uniq_musician_review'),
        ),
    ]
