# Generated by Django 5.2.13 on 2026-04-21 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('technique', models.CharField(blank=True, max_length=120)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_SUBASTA', 'En subasta'), ('VENDIDA', 'Vendida'), ('INACTIVA', 'Inactiva')], default='INACTIVA', max_length=20)),
                ('main_image_url', models.URLField(blank=True)),
                ('ai_tags', models.JSONField(blank=True, default=dict)),
                ('ai_description', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artists.artistprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['artwork', 'order'], name='artworks_ar_artwork_fbf06a_idx')],
                'constraints': [models.UniqueConstraint(fields=('artwork', 'order'), name='uniq_artwork_image_order')],
            },
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['status', '-created_at'], name='artworks_ar_status_5b775d_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['artist', '-created_at'], name='artworks_ar_artist__42c165_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category', '-created_at'], name='artworks_ar_categor_3adc22_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['price'], name='artworks_ar_price_a79096_idx'),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='artwork_price_gte_0'),
        ),
    ]
